from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from database_setup import States, Base, RegPrices, MagPrices

engine = create_engine('sqlite:///vingo.db')
# Bind the engine to the metadata of the Base class so that the
# declaratives can be accessed through a DBSession instance
Base.metadata.bind = engine

DBSession = sessionmaker(bind=engine)
# A DBSession() instance establishes all conversations with the database
# and represents a "staging zone" for all the objects loaded into the
# database session object. Any change made against the objects in the
# session won't be persisted into the database until you call
# session.commit(). If you're not happy about the changes, you can
# revert all of them back to the last commit by calling
# session.rollback()
session = DBSession()

# Prices for all the states

# Zone One - Regular Size Bottles

Zero1 = RegPrices(zone=1, bottles=0, price=0.00)
session.add(Zero1)
session.commit()
One1= RegPrices(zone=1, bottles=1, price=23.54)
session.add(One1)
session.commit()
Two1= RegPrices(zone=1, bottles=2, price=25.12)
session.add(Two1)
session.commit()
Three1= RegPrices(zone=1, bottles=3, price=28.33)
session.add(Three1)
session.commit()
Four1= RegPrices(zone=1, bottles=4, price=29.17)
session.add(Four1)
session.commit()
Five1= RegPrices(zone=1, bottles=5, price=30.00)
session.add(Five1)
session.commit()
Six1= RegPrices(zone=1, bottles=6, price=31.64)
session.add(Six1)
session.commit()
Seven1= RegPrices(zone=1, bottles=7, price=36.99)
session.add(Seven1)
session.commit()
Eight1= RegPrices(zone=1, bottles=8, price=38.62)
session.add(Eight1)
session.commit()
Nine1= RegPrices(zone=1, bottles=9, price=40.28)
session.add(Nine1)
session.commit()
Ten1= RegPrices(zone=1, bottles=10, price=41.94)
session.add(Ten1)
session.commit()
Eleven1= RegPrices(zone=1, bottles=11, price=42.77)
session.add(Eleven1)
session.commit()
Twelve1= RegPrices(zone=1, bottles=12, price=43.60)
session.add(Twelve1)
session.commit()

# Zone Two - Regular Size Bottles 

Zero2 = RegPrices(zone=2, bottles=0, price=0.00)
session.add(Zero2)
session.commit()
One2 = RegPrices(zone=2, bottles=1, price=25.19)
session.add(One2)
session.commit()
Two2 = RegPrices(zone=2, bottles=2, price=26.76)
session.add(Two2)
session.commit()
Three2 = RegPrices(zone=2, bottles=3, price=30.00)
session.add(Three2)
session.commit()
Four2 = RegPrices(zone=2, bottles=4, price=30.83)
session.add(Four2)
session.commit()
Five2 = RegPrices(zone=2, bottles=5, price=33.31)
session.add(Five2)
session.commit()
Six2 = RegPrices(zone=2, bottles=6, price=34.95)
session.add(Six2)
session.commit()
Seven2 = RegPrices(zone=2, bottles=7, price=41.13)
session.add(Seven2)
session.commit()
Eight2 = RegPrices(zone=2, bottles=8, price=44.43)
session.add(Eight2)
session.commit()
Nine2 = RegPrices(zone=2, bottles=9, price=46.90)
session.add(Nine2)
session.commit()
Ten2 = RegPrices(zone=2, bottles=10, price=49.37)
session.add(Ten2)
session.commit()
Eleven2 = RegPrices(zone=2, bottles=11, price=51.86)
session.add(Eleven2)
session.commit()
Twelve2 = RegPrices(zone=2, bottles=12, price=52.69)
session.add(Twelve2)
session.commit()

# Zone Three - Regular Size Bottles

Zero3 = RegPrices(zone=3, bottles=0, price=0.00)
session.add(Zero3)
session.commit()
One3 = RegPrices(zone=3, bottles=1, price=26.85)
session.add(One3)
session.commit()
Two3 = RegPrices(zone=3, bottles=2, price=28.42)
session.add(Two3)
session.commit()
Three3 = RegPrices(zone=3, bottles=3, price=33.32)
session.add(Three3)
session.commit()
Four3 = RegPrices(zone=3, bottles=4, price=36.61)
session.add(Four3)
session.commit()
Five3 = RegPrices(zone=3, bottles=5, price=39.92)
session.add(Five3)
session.commit()
Six3 = RegPrices(zone=3, bottles=6, price=42.41)
session.add(Six3)
session.commit()
Seven3 = RegPrices(zone=3, bottles=7, price=50.21)
session.add(Seven3)
session.commit()
Eight3 = RegPrices(zone=3, bottles=8, price=53.52)
session.add(Eight3)
session.commit()
Nine3 = RegPrices(zone=3, bottles=9, price=56.00)
session.add(Nine3)
session.commit()
Ten3 = RegPrices(zone=3, bottles=10, price=59.29)
session.add(Ten3)
session.commit()
Eleven3 = RegPrices(zone=3, bottles=11, price=62.61)
session.add(Eleven3)
session.commit()
Twelve3 = RegPrices(zone=3, bottles=12, price=65.92)
session.add(Twelve3)
session.commit()

# Zone Four - Regular Size Bottles

Zero4 = RegPrices(zone=4, bottles=0, price=0.00)
session.add(Zero4)
session.commit()
One4 = RegPrices(zone=4, bottles=1, price=31.14)
session.add(One4)
session.commit()
Two4 = RegPrices(zone=4, bottles=2, price=34.29)
session.add(Two4)
session.commit()
Three4 = RegPrices(zone=4, bottles=3, price=33.84)
session.add(Three4)
session.commit()
Four4 = RegPrices(zone=4, bottles=4, price=38.03)
session.add(Four4)
session.commit()
Five4 = RegPrices(zone=4, bottles=5, price=38.85)
session.add(Five4)
session.commit()
Six4 = RegPrices(zone=4, bottles=6, price=40.50)
session.add(Six4)
session.commit()
Seven4 = RegPrices(zone=4, bottles=7, price=46.47)
session.add(Seven4)
session.commit()
Eight4 = RegPrices(zone=4, bottles=8, price=48.10)
session.add(Eight4)
session.commit()
Nine4 = RegPrices(zone=4, bottles=9, price=49.76)
session.add(Nine4)
session.commit()
Ten4 = RegPrices(zone=4, bottles=10, price=51.42)
session.add(Ten4)
session.commit()
Eleven4 = RegPrices(zone=4, bottles=11, price=52.25)
session.add(Eleven4)
session.commit()
Twelve4 = RegPrices(zone=4, bottles=12, price=53.09)
session.add(Twelve4)
session.commit()

# Zone Five - Regular Prices

Zero5 = RegPrices(zone=5, bottles=0, price=0.00)
session.add(Zero5)
session.commit()
One5 = RegPrices(zone=5, bottles=1, price=25.38)
session.add(One5)
session.commit()
Two5 = RegPrices(zone=5, bottles=2, price=26.95)
session.add(Two5)
session.commit()
Three5 = RegPrices(zone=5, bottles=3, price=31.13)
session.add(Three5)
session.commit()
Four5 = RegPrices(zone=5, bottles=4, price=31.92)
session.add(Four5)
session.commit()
Five5 = RegPrices(zone=5, bottles=5, price=34.24)
session.add(Five5)
session.commit()
Six5 = RegPrices(zone=5, bottles=6, price=35.77)
session.add(Six5)
session.commit()
Seven5 = RegPrices(zone=5, bottles=7, price=40.75)
session.add(Seven5)
session.commit()
Eight5 = RegPrices(zone=5, bottles=8, price=43.84)
session.add(Eight5)
session.commit()
Nine5 = RegPrices(zone=5, bottles=9, price=46.16)
session.add(Nine5)
session.commit()
Ten5 = RegPrices(zone=5, bottles=10, price=48.48)
session.add(Ten5)
session.commit()
Eleven5 = RegPrices(zone=5, bottles=11, price=50.80)
session.add(Eleven5)
session.commit()
Twelve5 = RegPrices(zone=5, bottles=12, price=51.58)
session.add(Twelve5)
session.commit()

# Zone One - Mag Prices

MagZero1= MagPrices(zone=1, bottles=0, price=0.00)
session.add(MagZero1)
session.commit() 
MagOne1= MagPrices(zone=1, bottles=1, price=26.69)
session.add(MagOne1)
session.commit()
MagTwo1= MagPrices(zone=1, bottles=2, price=34.42)
session.add(MagTwo1)
session.commit()
MagThree1= MagPrices(zone=1, bottles=3, price=36.89)
session.add(MagThree1)
session.commit()
MagFour1= MagPrices(zone=1, bottles=4, price=48.59)
session.add(MagFour1)
session.commit()
MagFive1= MagPrices(zone=1, bottles=5, price=51.91)
session.add(MagFive1)
session.commit()
MagSix1= MagPrices(zone=1, bottles=6, price=53.57)
session.add(MagSix1)
session.commit()

# Zone Two - Mag Prices 

MagZero2= MagPrices(zone=2, bottles=0, price=0.00)
session.add(MagZero2)
session.commit()
MagOne2 = MagPrices(zone=2, bottles=1, price=28.33)
session.add(MagOne2)
session.commit()
MagTwo2 = MagPrices(zone=2, bottles=2, price=36.08)
session.add(MagTwo2)
session.commit()
MagThree2 = MagPrices(zone=2, bottles=3, price=40.19)
session.add(MagThree2)
session.commit()
MagFour2 = MagPrices(zone=2, bottles=4, price=54.40)
session.add(MagFour2)
session.commit()
MagFive2 = MagPrices(zone=2, bottles=5, price=59.35)
session.add(MagFive2)
session.commit()
MagSix2 = MagPrices(zone=2, bottles=6, price=63.38)
session.add(MagSix2)
session.commit()

# Zone Three - Mag Prices 

MagZero3= MagPrices(zone=3, bottles=0, price=0.00)
session.add(MagZero3)
session.commit()
MagOne3 = MagPrices(zone=3, bottles=1, price=30.00)
session.add(MagOne3)
session.commit()
MagTwo3 = MagPrices(zone=3, bottles=2, price=41.85)
session.add(MagTwo3)
session.commit()
MagThree3 = MagPrices(zone=3, bottles=3, price=47.66)
session.add(MagThree3)
session.commit()
MagFour3 = MagPrices(zone=3, bottles=4, price=63.49)
session.add(MagFour3)
session.commit()
MagFive3 = MagPrices(zone=3, bottles=5, price=69.27)
session.add(MagFive3)
session.commit()
MagSix3 = MagPrices(zone=3, bottles=6, price=75.90)
session.add(MagSix3)
session.commit()

# Zone Four - Mag Prices 

MagZero4= MagPrices(zone=4, bottles=0, price=0.00)
session.add(MagZero4)
session.commit()
MagOne4 = MagPrices(zone=4, bottles=1, price=34.29)
session.add(MagOne4)
session.commit()
MagTwo4 = MagPrices(zone=4, bottles=2, price=43.28)
session.add(MagTwo4)
session.commit()
MagThree4 = MagPrices(zone=4, bottles=3, price=45.75)
session.add(MagThree4)
session.commit()
MagFour4 = MagPrices(zone=4, bottles=4, price=58.08)
session.add(MagFour4)
session.commit()
MagFive4 = MagPrices(zone=4, bottles=5, price=61.39)
session.add(MagFive4)
session.commit()
MagSix4 = MagPrices(zone=4, bottles=6, price=63.06)
session.add(MagSix4)
session.commit()

# Zone Five - Mag Prices 

MagZero5= MagPrices(zone=5, bottles=0, price=0.00)
session.add(MagZero5)
session.commit()
MagOne5 = MagPrices(zone=5, bottles=1, price=28.53)
session.add(MagOne5)
session.commit()
MagTwo5 = MagPrices(zone=5, bottles=2, price=36.12)
session.add(MagTwo5)
session.commit()
MagThree5 = MagPrices(zone=5, bottles=3, price=39.97)
session.add(MagThree5)
session.commit()
MagFour5 = MagPrices(zone=5, bottles=4, price=53.81)
session.add(MagFour5)
session.commit()
MagFive5 = MagPrices(zone=5, bottles=5, price=58.45)
session.add(MagFive5)
session.commit()
MagSix5 = MagPrices(zone=5, bottles=6, price=61.55)
session.add(MagSix5)
session.commit()

print('Added prices to zones')