from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from database_setup import States, Base, RegPrices, MagPrices

engine = create_engine('sqlite:///vingo.db')
# Bind the engine to the metadata of the Base class so that the
# declaratives can be accessed through a DBSession instance
Base.metadata.bind = engine

DBSession = sessionmaker(bind=engine)
# A DBSession() instance establishes all conversations with the database
# and represents a "staging zone" for all the objects loaded into the
# database session object. Any change made against the objects in the
# session won't be persisted into the database until you call
# session.commit(). If you're not happy about the changes, you can
# revert all of them back to the last commit by calling
# session.rollback()
session = DBSession()

# Fill States table

# Zone 1 States 
CT = States(name='CT', transit='2 business days', carrier='UPS', zone=1)
session.add(CT)
session.commit()
DC = States(name='DC', transit='3 business days', carrier='UPS', zone=1)
session.add(DC)
session.commit()
DE = States(name='DE', transit='3 business days', carrier='UPS', zone=1)
session.add(DE)
session.commit()
MA = States(name='MA', transit='2 business days', carrier='UPS', zone=1)
session.add(MA)
session.commit()
MD = States(name='MD', transit='3 business days', carrier='FedEx', zone=1)
session.add(MD)
session.commit()
ME = States(name='ME', transit='3 business days', carrier='UPS', zone=1)
session.add(ME)
session.commit()
NH = States(name='NH', transit='3 business days', carrier='UPS', zone=1)
session.add(NH)
session.commit()
NJ = States(name='NJ', transit='2 business days', carrier='UPS', zone=1)
session.add(NJ)
session.commit()
OH = States(name='OH', transit='3 business days', carrier='UPS', zone=1)
session.add(OH)
session.commit()
PA = States(name='PA', transit='2-3 business days', carrier='UPS', zone=1)
session.add(PA)
session.commit()
RI = States(name='RI', transit='3 business days', carrier='UPS', zone=1)
session.add(RI)
session.commit()
VA = States(name='VA', transit='3 business days', carrier='UPS', zone=1)
session.add(VA)
session.commit()
VT = States(name='VT', transit='2 business days', carrier='FedEx', zone=1)
session.add(VT)
session.commit()
WV = States(name='WV', transit='3 business days', carrier='UPS', zone=1)
session.add(WV)
session.commit()

# Zone 2 States
FL = States(name='FL', transit='4 business days', carrier='UPS', zone=2)
session.add(FL)
session.commit()
GA = States(name='GA', transit='3-4 business days', carrier='UPS', zone=2)
session.add(GA)
session.commit()
IA = States(name='IA', transit='4 business days', carrier='UPS', zone=2)
session.add(IA)
session.commit()
IN = States(name='IN', transit='3 business days', carrier='UPS', zone=2)
session.add(IN)
session.commit()
LA = States(name='LA', transit='4-5 business days', carrier='UPS', zone=2)
session.add(LA)
session.commit()
MI = States(name='MI', transit='3 business days', carrier='UPS', zone=2)
session.add(MI)
session.commit()
MN = States(name='MN', transit='4-5 business days', carrier='UPS', zone=2)
session.add(MN)
session.commit()
MO = States(name='MO', transit='4 business days', carrier='UPS', zone=2)
session.add(MO)
session.commit()
NC = States(name='NC', transit='3 business days', carrier='UPS', zone=2)
session.add(NC)
session.commit()
SC = States(name='SC', transit='3-4 business days', carrier='UPS', zone=2)
session.add(SC)
session.commit()
TN = States(name='TN', transit='3 business days', carrier='UPS', zone=2)
session.add(TN)
session.commit()
WI = States(name='WI', transit='4 business days', carrier='UPS', zone=2)
session.add(WI)
session.commit()

# Zone 3 States
AZ = States(name='AZ', transit='5 business days', carrier='UPS', zone=3)
session.add(AZ)
session.commit()
CA = States(name='CA', transit='5-6 business days', carrier='UPS', zone=3)
session.add(CA)
session.commit()
CO = States(name='CO', transit='5-6 business days', carrier='UPS', zone=3)
session.add(CO)
session.commit()
ID = States(name='ID', transit='6 business days', carrier='UPS', zone=3)
session.add(ID)
session.commit()
KS = States(name='KS', transit='4 business days', carrier='UPS', zone=3)
session.add(KS)
session.commit()
MT = States(name='MT', transit='6 business days', carrier='UPS', zone=3)
session.add(MT)
session.commit()
NE = States(name='NE', transit='4-5 business days', carrier='UPS', zone=3)
session.add(NE)
session.commit()
ND = States(name='ND', transit='5 business days', carrier='UPS', zone=3)
session.add(ND)
session.commit()
NM = States(name='NM', transit='5-6 business days', carrier='UPS', zone=3)
session.add(NM)
session.commit()
NV = States(name='NV', transit='6 business days', carrier='UPS', zone=3)
session.add(NV)
session.commit()
OR = States(name='OR', transit='6 business days', carrier='UPS', zone=3)
session.add(OR)
session.commit()
SD = States(name='SD', transit='5 business days', carrier='UPS', zone=3)
session.add(SD)
session.commit()
WA = States(name='WA', transit='6 business days', carrier='UPS', zone=3)
session.add(WA)
session.commit()
WY = States(name='WY', transit='5-6 business days', carrier='UPS', zone=3)
session.add(CA)
session.commit()


#Zone 4 states (Texas and Alabama)
TX = States(name='TX', transit='7-9 business days', carrier='LSO', zone=4)
session.add(TX)
session.commit()
OK = States(name='OK', transit='7-9 business days', carrier='LSO', zone=4)
session.add(OK)
session.commit()

# Zone 5 States (Illinois)
IL = States(name='IL', transit='7-9 business days', carrier='UDS', zone=5)
session.add(IL)
session.commit()

print('added states to zones')
